version: '3'

services:
  arcade-pxt:
    image: node:latest
    volumes:
      - ./pxt-arcade:/app
    ports:
      - 3233:3233
      - 3232:3232
    working_dir: /app
    command: 
      - /bin/sh
      - -c
      - |
        npm install -g pxt
        npm install
        pxt serve -h 0.0.0.0
